global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_micrometer'
    metrics_path: '/manage/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.1.15:8081']